### PR TITLE
packer-rocm/rocDecode: packages

### PR DESCRIPTION
**Pull request by joshlay2amd**
Inspiration: https://github.com/ROCm/rocDecode/commit/859103755a8d8dffd4cc04f87375dfd0f2f30629

Extending the packages handled by the ROCm play while reducing those in `user-data`. Surprisingly, this helps iteration speed. `cloud-init` processes in series while Ansible can process lists of packages at once.

Other process improvements:

- The 'requirement' installation task is now delayed after repository setup. Allows the ROCm/amdgpu repositories to provide any of them, instead of just the Linux distribution.
- Package downgrades are permitted for requests with the 'extra' and 'amdgpu' packages

The very-specific path has been tested. Need to ensure defaults still behave as expected.

### CODE REVIEW

**Comment by joshlay** [comment]
Commits [6f68a23](https://github.com/nod-ai/ADA/pull/60/commits/6f68a238c51c8c6714ade049c26d2d68d8e5468a) and beyond include a refactor from the `rocm` play to an `amdgpu_install` role.

This attempts to do the installation for selected components with the _scripted_ method.

Choosing a specific build seemed ineffective, landing on latest. More to follow.

**Comment by joshlay2amd** [comment]
Commits [6f68a23](https://github.com/nod-ai/ADA/pull/60/commits/6f68a238c51c8c6714ade049c26d2d68d8e5468a) and beyond include a refactor from the `rocm` play to an `amdgpu_install` role.

This attempts to do the installation for selected components with the _scripted_ method. 

Choosing a specific build seemed ineffective, landing on latest despite a specific build provided. I believe simply mishandled changing the build declarations from two keys in a dictionary (`amdgpu_install_repos`) to independent strings.

More to follow.

**Comment by joshlay2amd** [comment]
A combination of issues - asking for versioned packages that should be handled by `amdgpu-install`... and not passing the build numbers through correctly _[as hinted in my last post]_

Now able to build/deploy an image with very-specific release/builds and the `internal` package. Need to test the GA path next.

**Comment by joshlay2amd** [comment]
Built an image with mostly-defaults, example:

```
ansible-playbook packer-rocm/playbooks/build.yml \
        -t build \
        -e hidden=false \
        -e rocm_builder_cpus=8 \
        -e rocm_builder_disk="40G"
```

Inspecting the archive, I found an oversight - the release/build defaults slipped. I _intended_ `6.2.2` _(for consistency with some testing)_... but had put into motion changes for `6.2.3`. Now consistent! Added `MAINTENANCE.md` as a warning 😄 

Now can do both typical paths with `amdgpu-install`: latest release, very specific releases. I believe this can be merged _technically_ speaking. May benefit from well-rested review.

**Pull request merged**
